Repository phpro/grumphp, pull requests merged in 2018-11, with the labels that each got.

#573 Added parameter to toggle show info
  doc/tasks/psalm.md
  spec/Task/PsalmSpec.php
  src/Task/Psalm.php
Labels: enhancement

#543 Allow PHPLint to handle large number of files
  composer.json
  spec/Task/PhpLintSpec.php
  src/Task/PhpLint.php
Labels: enhancement

#558 Add phpunit bridge
  README.md
  composer.json
  doc/tasks.md
  doc/tasks/phpunitbridge.md
  resources/config/tasks.yml
  spec/Task/PhpunitBridgeSpec.php
  src/Task/PhpunitBridge.php
Labels: new feature

#563 Add missing property
  doc/tasks/git_branch_name.md
  spec/Task/Git/BranchNameSpec.php
Labels: Documentation

#570 Add ignore patterns for PHPLint task
  doc/tasks/phplint.md
  spec/Task/PhpLintSpec.php
  src/Task/PhpLint.php
Labels: enhancement

#562 Add whitelist and blacklist to GitBranchName
  doc/tasks/git_branch_name.md
  spec/Task/Git/BranchNameSpec.php
  src/Task/Git/BranchName.php
Labels: enhancement
