Repository phpro/grumphp, pull requests merged in 2018-03, with the labels that each got.

#472 Fixed notice if repositories is not defined
  spec/Task/ComposerSpec.php
  src/Task/Composer.php
Labels: enhancement

#473 Made "git diff" behave more predictably
  resources/hooks/local/commit-msg
  resources/hooks/local/pre-commit
  resources/hooks/vagrant/commit-msg
  resources/hooks/vagrant/pre-commit
Labels: enhancement

#474 Add ignore-msi-with-no-mutations
  src/Task/Infection.php
Labels: enhancement

#476 Changed phpcpd "names_exclude" option
  spec/Task/PhpCpdSpec.php
  src/Task/PhpCpd.php
Labels: enhancement

#459 Add support for custom location of .git directory
  src/Console/Helper/PathsHelper.php
Labels: enhancement

#461 Use correct path to .git/COMMIT_EDITMSG when using non-standard .git dir location
  src/Console/Command/Git/CommitMsgCommand.php
Labels: bug

#483 Docs: Run same task twice with different configuration
  doc/tasks.md
Labels: Documentation
