Repository phpro/grumphp, pull requests merged in 2018-10, with the labels that each got.

#539 feat: Add additional info parameter
  doc/parameters.md
  resources/config/parameters.yml
  spec/Configuration/GrumPHPSpec.php
  spec/Console/Helper/TaskRunnerHelperSpec.php
  src/Configuration/GrumPHP.php
  src/Console/Helper/TaskRunnerHelper.php
Labels: new feature

#557 Add PHP 7.2 EOL to PHP version checker
  doc/tasks/phpversion.md
  resources/config/util.yml
Labels: enhancement

#559 Host our own version of the symfony XSDs
  test/fixtures/linters/xml/xsd-url-invalid.xml
  test/fixtures/linters/xml/xsd-url-valid.xml
Labels: bug
