Repository phpro/grumphp, pull requests merged in 2018-07, with the labels that each got.

#525 Make detection of strict types compatible with PhpParser 4.
  src/Parser/Php/Visitor/DeclareStrictTypesVisitor.php
Labels: enhancement

#522 Correct package-name of phan
  composer.json
  doc/tasks/phan.md
Labels: Documentation

#520 Only run question helper in interactive mode
  src/Console/Command/ConfigureCommand.php
Labels: bug

#510 Add psalm
  README.md
  composer.json
  doc/tasks.md
  doc/tasks/psalm.md
  resources/config/tasks.yml
  spec/Task/PsalmSpec.php
  src/Task/Psalm.php
Labels: new feature
