Repository phpro/grumphp, pull requests merged in 2019-11, with the labels that each got.

#695 fix(commit-message): CheckTypeScope with a special prefix
  spec/Task/Git/CommitMessageSpec.php
  src/Task/Git/CommitMessage.php
Labels: enhancement

#697 Pass array of directories to phpcpd
  doc/tasks/phpcpd.md
  src/Task/PhpCpd.php
Labels: enhancement

#691 Adding PSR12 to documentation
  doc/tasks/phpcs.md
Labels: Documentation

#701 Add support symfony 5, add support php74, drop support php71
  .travis.yml
  appveyor.yml
  composer.json
  grumphp.yml.dist
  resources/config/console.yml
  resources/config/services.yml
  resources/config/util.yml
  spec/Console/Helper/TaskRunnerHelperSpec.php
  spec/Event/EventDispatcherFactorySpec.php
  spec/Event/RunnerEventSpec.php
  spec/Event/Subscriber/ProgressSubscriberSpec.php
  spec/Event/TaskEventSpec.php
  spec/Runner/TaskRunnerSpec.php
  src/Console/Command/ConfigureCommand.php
  src/Console/Command/Git/CommitMsgCommand.php
  src/Console/Command/Git/DeInitCommand.php
  src/Console/Command/Git/InitCommand.php
  src/Console/Command/Git/PreCommitCommand.php
  src/Console/Command/RunCommand.php
  src/Console/Helper/TaskRunnerHelper.php
  src/Event/Dispatcher/Bridge/SymfonyEventDispatcher.php
  src/Event/Dispatcher/EventDispatcherInterface.php
  src/Event/Event.php
  src/Event/EventDispatcherFactory.php
  src/Event/RunnerEvent.php
  src/Event/Subscriber/ProgressSubscriber.php
  src/Event/TaskEvent.php
  src/Runner/TaskRunner.php
  test/Symfony/FilesystemTestCase.php
  test/Unit/Locator/GuessedPathsLocatorTest.php
  test/Unit/Util/FilesystemTest.php
  test/Unit/Util/PathsTest.php
Labels: enhancement

#653 Add silent argument to npm task
  doc/tasks/npm_script.md
  spec/Task/NpmScriptSpec.php
  src/Task/NpmScript.php
Labels: enhancement

#675 Improved composer plugin
  bump
  doc/installation/exotic.md
  resources/config/console.yml
  src/Composer/DevelopmentIntegrator.php
  src/Composer/GrumPHPPlugin.php
  src/Configuration/ContainerBuilder.php
  src/Console/Command/ConfigureCommand.php
  src/Util/Paths.php
  test/E2E/AbstractE2ETestCase.php
Labels: Composer Plugin, enhancement
