Repository phpro/grumphp, pull requests merged in 2019-05, with the labels that each got.

#631 Add descriptions to the git:* commands
  src/Console/Command/Git/CommitMsgCommand.php
  src/Console/Command/Git/DeInitCommand.php
  src/Console/Command/Git/InitCommand.php
  src/Console/Command/Git/PreCommitCommand.php
Labels: enhancement

#629 Adds PHP7 type hinting where missing
  src/Collection/TaskResultCollection.php
  src/Console/Command/ConfigureCommand.php
  src/Console/Command/Git/PreCommitCommand.php
  src/Console/Command/RunCommand.php
  src/Util/Str.php
Labels: enhancement

#634 Implement the Phpcs exclude option
  doc/tasks/phpcs.md
  spec/Task/PhpcsSpec.php
  src/Task/Phpcs.php
Labels: enhancement

#636 Fix typo
  doc/tasks/phpcsfixer2.md
Labels: Documentation

#632 Task TwigCs
  README.md
  composer.json
  doc/tasks.md
  doc/tasks/twigcs.md
  resources/config/tasks.yml
  spec/Task/TwigCsSpec.php
  src/Task/TwigCs.php
Labels: new feature

#587 Provide option to run a single/list of tasks from the config
  doc/commands.md
  spec/Collection/TasksCollectionSpec.php
  spec/Runner/TaskRunnerContextSpec.php
  spec/Runner/TaskRunnerSpec.php
  spec/Util/StrSpec.php
  src/Collection/TasksCollection.php
  src/Console/Command/RunCommand.php
  src/Runner/TaskRunner.php
  src/Runner/TaskRunnerContext.php
  src/Util/Str.php
Labels: enhancement

#596 Add task composer normalize
  README.md
  composer.json
  doc/tasks.md
  doc/tasks/composer_normalize.md
  resources/config/tasks.yml
  spec/Task/ComposerNormalizeSpec.php
  src/Task/ComposerNormalize.php
Labels: new feature

#618 #615, Support other PHP executable
  README.md
  appveyor.yml
  composer.json
  doc/parameters.md
  resources/config/parameters.yml
  resources/hooks/local/commit-msg
  resources/hooks/local/pre-commit
  resources/hooks/vagrant/commit-msg
  resources/hooks/vagrant/pre-commit
  spec/Configuration/GrumPHPSpec.php
  spec/Process/ProcessUtilsSpec.php
  src/Console/Command/Git/InitCommand.php
  src/Process/ProcessUtils.php
  test/Bootstrap.php
  test/E2E/AbstractE2ETestCase.php
  test/E2E/GitHookParametersTest.php
Labels: enhancement

#637 Fix issue when no --tasks are specified
  spec/Util/StrSpec.php
  src/Util/Str.php
Labels: bug

#640 Add ignore funcs
  doc/tasks/phpmnd.md
  spec/Task/PhpMndSpec.php
  src/Task/PhpMnd.php
Labels: enhancement

#638 Improve e2e time on appveyor
  .gitignore
  .travis.yml
  appveyor.yml
  composer.json
  doc/tasks/paratest.md
  grumphp.yml.dist
  spec/Process/ProcessBuilderSpec.php
  spec/Process/ProcessFactorySpec.php
  spec/Runner/TaskRunnerSpec.php
  spec/Task/ParatestSpec.php
  src/Task/Paratest.php
  test/Bootstrap.php
  test/E2E/AbstractE2ETestCase.php
  test/Unit/Linter/Json/JsonLinterTest.php
  test/Unit/Linter/Xml/XmlLinterTest.php
  test/Unit/Linter/Yaml/YamlLinterTest.php
  test/fixtures/e2e/tasks/ValidatePathsTask.php
  test/fixtures/linters/yaml/constant-support.yml
Labels: enhancement

#616 Upgrade to php 7.1
  composer.json
  src/Collection/ProcessArgumentsCollection.php
  src/Collection/TasksCollection.php
  src/Collection/TestSuiteCollection.php
  src/Composer/DevelopmentIntegrator.php
  src/Composer/GrumPHPPlugin.php
  src/Configuration/Compiler/ExtensionCompilerPass.php
  src/Configuration/Compiler/PhpParserCompilerPass.php
  src/Configuration/Compiler/TaskCompilerPass.php
  src/Configuration/Compiler/TestSuiteCompilerPass.php
  src/Configuration/GrumPHP.php
  src/Console/Application.php
  src/Console/Command/ConfigureCommand.php
  src/Console/Command/Git/CommitMsgCommand.php
  src/Console/Command/Git/DeInitCommand.php
  src/Console/Command/Git/InitCommand.php
  src/Console/Command/Git/PreCommitCommand.php
  src/Console/Command/RunCommand.php
  src/Console/Helper/ComposerHelper.php
  src/Console/Helper/PathsHelper.php
  src/Console/Helper/TaskRunnerHelper.php
  src/Event/Subscriber/ProgressSubscriber.php
  src/Event/Subscriber/StashUnstagedChangesSubscriber.php
  src/Formatter/PhpCsFixerFormatter.php
  src/IO/ConsoleIO.php
  src/IO/NullIO.php
  src/Linter/Json/JsonLinter.php
  src/Linter/Xml/XmlLinter.php
  src/Linter/Yaml/YamlLinter.php
  src/Locator/ConfigurationFile.php
  src/Parser/Php/Configurator/TraverserConfigurator.php
  src/Parser/Php/PhpParser.php
  src/Parser/Php/Visitor/AbstractVisitor.php
  src/Parser/Php/Visitor/DeclareStrictTypesVisitor.php
  src/Parser/Php/Visitor/ForbiddenClassMethodCallsVisitor.php
  src/Parser/Php/Visitor/ForbiddenFunctionCallsVisitor.php
  src/Parser/Php/Visitor/ForbiddenStaticMethodCallsVisitor.php
  src/Parser/Php/Visitor/NeverUseElseVisitor.php
  src/Parser/Php/Visitor/NoExitStatementsVisitor.php
  src/Process/AsyncProcessRunner.php
  src/Process/ProcessBuilder.php
  src/Runner/TaskRunner.php
  src/Runner/TaskRunnerContext.php
  src/Task/AbstractLinterTask.php
  src/Task/Git/CommitMessage.php
  src/Task/PhpunitBridge.php
  src/Task/Progpilot.php
  src/Task/Psalm.php
  src/Task/Shell.php
  src/Util/Composer.php
  src/Util/Regex.php
  src/Util/Str.php
Labels: BC BREAK

#556 Move composer dependency to dev
  composer.json
  spec/Console/Helper/ComposerHelperSpec.php
  spec/Locator/ConfigurationFileSpec.php
  spec/Util/ComposerFileSpec.php
  src/Console/Application.php
  src/Console/Command/ConfigureCommand.php
  src/Console/Helper/ComposerHelper.php
  src/Locator/ConfigurationFile.php
  src/Util/Composer.php
  src/Util/ComposerFile.php
Labels: enhancement

#642 Normalize composer.json
  composer.json
Labels: enhancement

#643 Only show project files when project is in subfolder
  resources/config/util.yml
  spec/Console/Helper/PathsHelperSpec.php
  spec/Locator/ChangedFilesSpec.php
  spec/Task/CloverCoverageSpec.php
  spec/Util/FilesystemSpec.php
  src/Composer/DevelopmentIntegrator.php
  src/Configuration/ContainerFactory.php
  src/Configuration/GrumPHP.php
  src/Console/Application.php
  src/Console/Helper/PathsHelper.php
  src/Locator/ChangedFiles.php
  src/Locator/ConfigurationFile.php
  src/Util/Filesystem.php
  test/E2E/FolderStructuresTest.php
  test/Unit/Linter/Json/JsonLinterTest.php
  test/Unit/Linter/Yaml/YamlLinterTest.php
  test/Unit/Util/FilesystemTest.php
Labels: BC BREAK, enhancement
