Repository phpro/grumphp, pull requests merged in 2019-04, with the labels that each got.

#620 Update phpcs.md
  doc/tasks/phpcs.md
Labels: Documentation

#623 Add EasyCodingStandard extension
  doc/extensions.md
Labels: Documentation

#626 Fixes return type of `ConfigureCommand::pathValidator`
  src/Console/Command/ConfigureCommand.php
Labels: bug

#617 Add Paratest task
  README.md
  composer.json
  doc/tasks.md
  doc/tasks/paratest.md
  resources/config/tasks.yml
  spec/Task/ParatestSpec.php
  src/Task/Paratest.php
Labels: new feature

#611 End 2 end tests
  .travis.yml
  appveyor.yml
  composer.json
  grumphp.yml.dist
  phpunit.xml.dist
  test/Bootstrap.php
  test/E2E/AbstractE2ETestCase.php
  test/E2E/FolderStructuresTest.php
  test/Unit/Linter/Json/JsonLinterTest.php
  test/Unit/Linter/Xml/XmlLinterTest.php
  test/Unit/Linter/Yaml/YamlLinterTest.php
  test/Unit/Parser/Php/Visitor/AbstractVisitorTest.php
  test/Unit/Parser/Php/Visitor/DeclareStrictTypesVisitorTest.php
  test/Unit/Parser/Php/Visitor/ForbiddenClassMethodCallsVisitorTest.php
  test/Unit/Parser/Php/Visitor/ForbiddenFunctionCallsVisitorTest.php
  test/Unit/Parser/Php/Visitor/ForbiddenStaticMethodCallsVisitorTest.php
  test/Unit/Parser/Php/Visitor/NeverUseElseVisitorTest.php
  test/Unit/Parser/Php/Visitor/NoExitStatementsVisitorTest.php
  test/fixtures/e2e/tasks/ValidatePathsTask.php
Labels: new feature

#627 Improve level parameter of PhpStan task
  spec/Collection/ProcessArgumentsCollectionSpec.php
  src/Collection/ProcessArgumentsCollection.php
  src/Task/PhpStan.php
Labels: enhancement

#625 add Ecs (EasyCodingStandard) Task
  composer.json
  doc/tasks.md
  doc/tasks/ecs.md
  resources/config/tasks.yml
  spec/Task/EcsSpec.php
  src/Task/Ecs.php
Labels: new feature
