Repository phpro/grumphp, pull requests merged in 2019-03, with the labels that each got.

#604 Bump up security-checker version to ^5.0 #603
  composer.json
Labels: enhancement

#598 Create failed.txt
  resources/ascii/failed.txt
Labels: enhancement

#597 Create succeeded.txt
  doc/parameters.md
  resources/ascii/succeeded.txt
Labels: enhancement

#544 Added vagrant_dir and vagrant_project_dir parameters
  README.md
  doc/parameters.md
  resources/config/parameters.yml
  resources/hooks/vagrant/commit-msg
  resources/hooks/vagrant/pre-commit
  spec/Configuration/GrumPHPSpec.php
  src/Configuration/GrumPHP.php
  src/Console/Command/Git/InitCommand.php
Labels: new feature

#591 Add memory-limit parameter to PhpStan
  doc/tasks/phpstan.md
  spec/Task/PhpStanSpec.php
  src/Task/PhpStan.php
Labels: enhancement

#608 Fix CI
  spec/Event/Subscriber/ProgressSubscriberSpec.php
Labels: enhancement

#609 Bugfix: convert splFileInfo to string
  spec/Collection/ProcessArgumentsCollectionSpec.php
  spec/Task/PhpCsFixerSpec.php
  src/Collection/ProcessArgumentsCollection.php
  src/Process/ProcessFactory.php
  src/Task/AbstractPhpCsFixerTask.php
Labels: bug

#610 Fix the code example markup for this disable documentation
  doc/parameters.md
Labels: Documentation
