Repository phpro/grumphp, pull requests merged in 2020-06, with the labels that each got.

#773 Fix invalid config generation
  src/Console/Command/ConfigureCommand.php
Labels: bug

#775 Typo: Remove extra space in output text of FixerUpper
  src/Fixer/FixerUpper.php
Labels: enhancement

#776 paratest: Add support for '--coverage-clover' and '--coverage-php'
  doc/tasks/paratest.md
  src/Task/Paratest.php
  test/Unit/Task/ParatestTest.php
Labels: enhancement

#774 Add ESLint Task
  doc/tasks.md
  doc/tasks/eslint.md
  resources/config/formatter.yml
  resources/config/tasks.yml
  spec/Formatter/ESLintFormatterSpec.php
  src/Formatter/ESLintFormatter.php
  src/Task/ESLint.php
  test/Unit/Task/ESLintTest.php
Labels: new feature
