Repository phpro/grumphp, pull requests merged in 2020-02, with the labels that each got.

#731 Remove tasks from readme
  README.md
Labels: Documentation

#737 Fixed label output
  src/Configuration/Compiler/TaskCompilerPass.php
Labels: bug

#740 Removed unused parameters for grumphp.yml.dist
  grumphp.yml.dist
Labels: enhancement

#739 Added support for phar executables
  doc/tasks/psalm.md
  spec/Locator/ExternalCommandSpec.php
  src/Locator/ExternalCommand.php
Labels: enhancement
