Repository phpro/grumphp, pull requests merged in 2020-10, with the labels that each got.

#823 Remove obsolete sprintf from ExecutableNotFoundException callback
  src/Locator/ExternalCommand.php
Labels: enhancement

#824 Consistently use yml instead of yaml extension in documentation
  doc/installation/exotic.md
  doc/runner.md
  doc/tasks.md
Labels: enhancement

#826 Remove unknown options from phpcpd task documentation
  doc/tasks/phpcpd.md
Labels: Documentation

#825 Use the maintained version of php-parallel-lint
  composer.json
Labels: enhancement

#827 Twig min version
  doc/tasks/twigcs.md
Labels: Documentation

#828 Made Ecs task fixable
  src/Task/Ecs.php
  test/Unit/Task/EcsTest.php
Labels: enhancement

#830 fix(CommitMessage): merge branch and tag syntax was failing with GitFlow
  src/Task/Git/CommitMessage.php
  test/Unit/Task/Git/CommitMessageTest.php
Labels: enhancement

#818 Improve no-ansi reporting
  composer.json
  resources/config/runner.yml
  src/Runner/Ci/CiDetector.php
  src/Runner/Reporting/TaskResultsReporter.php
  test/Unit/Runner/Ci/CiDetectorTest.php
Labels: enhancement

#829 Allow merging tasks
  src/Configuration/Configuration.php
Labels: enhancement

#831 Change phpstans default level
  doc/tasks/phpstan.md
  src/Task/PhpStan.php
  test/Unit/Task/PhpStanTest.php
Labels: bug, enhancement
