Repository phpro/grumphp, pull requests merged in 2020-07, with the labels that each got.

#782 Make Travis green again on PHP 8!
  .travis.yml
Labels: enhancement

#780 Fix command escaping
  doc/parameters.md
  spec/Formatter/ESLintFormatterSpec.php
  spec/Formatter/PhpCsFixerFormatterSpec.php
  spec/Process/ProcessBuilderSpec.php
  spec/Process/ProcessUtilsSpec.php
  src/Composer/DevelopmentIntegrator.php
  src/Configuration/Configuration.php
  src/Console/Command/Git/InitCommand.php
  src/Formatter/PhpCsFixerFormatter.php
  src/Process/ProcessUtils.php
  src/Task/PhpCsFixer.php
  test/E2E/AbstractE2ETestCase.php
  test/E2E/GitHookParametersTest.php
  test/Unit/Task/PhpCsFixerTest.php
Labels: bug, enhancement

#784 Suggest command to fix composer_normalize errors
  resources/config/formatter.yml
  resources/config/tasks.yml
  src/Formatter/ComposerNormalizeFormatter.php
  src/Task/ComposerNormalize.php
  test/Unit/Task/ComposerNormalizeTest.php
Labels: enhancement

#788 Fix broken stdin
  src/IO/ConsoleIO.php
Labels: bug

#766 [phpmd] Allow setting output format to ansi
  doc/tasks/phpmd.md
  src/Task/PhpMd.php
  test/Unit/Task/PhpMdTest.php
Labels: enhancement
