Repository phpro/grumphp, pull requests merged in 2020-12, with the labels that each got.

#854 Fix Paratest 6.1.1 syntax
  composer.json
  src/Task/Paratest.php
  test/Unit/Task/ParatestTest.php
Labels: enhancement

#841 Implement refactored formatter options for Deptrac >= v0.9.0
  doc/tasks/deptrac.md
  src/Task/Deptrac.php
  test/Unit/Task/DeptracTest.php
Labels: new feature

#851 Fix git init command in parameters.md
  doc/parameters.md
Labels: Documentation

#852 Upgrade to amphp/parallel-functions 1.0
  composer.json
Labels: enhancement
