Repository phpro/grumphp, pull requests merged in 2020-08, with the labels that each got.

#794 Improved fixable tasks
  doc/tasks/composer_normalize.md
  doc/tasks/eslint.md
  doc/tasks/phpcs.md
  doc/tasks/phpcsfixer.md
  resources/config/formatter.yml
  resources/config/tasks.yml
  spec/Exception/ExecutableNotFoundExceptionSpec.php
  spec/Formatter/ESLintFormatterSpec.php
  spec/Formatter/PhpCsFixerFormatterSpec.php
  spec/Formatter/PhpcsFormatterSpec.php
  spec/Runner/FixableTaskResultSpec.php
  spec/Runner/TaskResultSpec.php
  src/Exception/ExecutableNotFoundException.php
  src/Fixer/Provider/FixableProcessResultProvider.php
  src/Formatter/ComposerNormalizeFormatter.php
  src/Formatter/ESLintFormatter.php
  src/Formatter/PhpCsFixerFormatter.php
  src/Formatter/PhpcsFormatter.php
  src/Locator/ExternalCommand.php
  src/Runner/FixableTaskResult.php
  src/Runner/TaskResult.php
  src/Runner/TaskResultInterface.php
  src/Task/ComposerNormalize.php
  src/Task/ESLint.php
  src/Task/PhpCsFixer.php
  src/Task/Phpcs.php
  test/Unit/Fixer/Provider/FixableProcessResultProviderTest.php
  test/Unit/Task/ComposerNormalizeTest.php
  test/Unit/Task/ESLintTest.php
  test/Unit/Task/PhpCsFixerTest.php
  test/Unit/Task/PhpcsTest.php
Labels: enhancement

#795 Create smart backups of existing git hooks
  README.md
  src/Console/Command/Git/InitCommand.php
  src/Util/Filesystem.php
  test/Unit/Util/FilesystemTest.php
Labels: new feature

#797 Update PhpCpd names-exclude property
  src/Task/PhpCpd.php
  test/Unit/Task/PhpCpdTest.php
Labels: enhancement

#796 Improved file passing tools
  spec/Collection/FilesCollectionSpec.php
  spec/Exception/ProcessExceptionSpec.php
  src/Collection/FilesCollection.php
  src/Exception/ProcessException.php
  src/Process/InputWritingProcessRunner.php
  src/Process/TmpFileUsingProcessRunner.php
  src/Task/PhpLint.php
  src/Task/Phpcs.php
  src/Test/Task/AbstractExternalTaskTestCase.php
  test/Unit/Task/PhpcsTest.php
Labels: enhancement

#801 Provide a stdin way of configuring files that need to be validated by GrumPHP
  doc/commands.md
  resources/config/console.yml
  resources/config/locators.yml
  resources/config/services.yml
  spec/IO/ConsoleIOSpec.php
  spec/Locator/ListedFilesSpec.php
  spec/Locator/RegisteredFilesSpec.php
  spec/Locator/StdInFilesSpec.php
  src/Console/Command/Git/CommitMsgCommand.php
  src/Console/Command/Git/PreCommitCommand.php
  src/Console/Command/RunCommand.php
  src/IO/ConsoleIO.php
  src/Locator/ListedFiles.php
  src/Locator/RegisteredFiles.php
  src/Locator/StdInFiles.php
Labels: new feature

#804 Add `match_word` option to git blacklist task
  doc/tasks/git_blacklist.md
  src/Task/Git/Blacklist.php
  test/Unit/Task/Git/BlacklistTest.php
Labels: enhancement

#806 Fix properties for PhpCpd v6
  doc/tasks/phpcpd.md
  src/Task/PhpCpd.php
  test/Unit/Task/PhpCpdTest.php
Labels: enhancement

#807 Phpstan: use_grumphp_paths option
  doc/tasks/phpstan.md
  src/Task/PhpStan.php
  src/Test/Task/AbstractExternalTaskTestCase.php
  test/Unit/Task/PhpStanTest.php
Labels: enhancement

#808 minor git_commit_message improvements
  resources/config/tasks.yml
  src/Task/Git/CommitMessage.php
  test/Unit/Task/Git/CommitMessageTest.php
Labels: bug, enhancement

#809 ecs: rename whitelist_patterns to paths and add files_on_pre_commit
  doc/tasks/ecs.md
  src/Task/Ecs.php
  test/Unit/Task/EcsTest.php
Labels: BC BREAK, enhancement

#810 Nette Tester task
  composer.json
  doc/tasks.md
  doc/tasks/tester.md
  resources/config/tasks.yml
  src/Task/Tester.php
  test/Unit/Task/TesterTest.php
Labels: new feature
