Repository phpro/grumphp, pull requests merged in 2020-11, with the labels that each got.

#834 Fixed regex special characters not escaped in example code.
  doc/tasks/git_blacklist.md
Labels: Documentation

#844 Allow PHP8
  .travis.yml
  composer.json
  src/Composer/GrumPHPPlugin.php
Labels: enhancement

#846 Remove travis in favour of GA
  .github/workflows/grumphp.yml
  .gitignore
  .travis.yml
  README.md
  appveyor.yml
  resources/config/util.yml
  test/E2E/AbstractE2ETestCase.php
  test/Unit/Runner/Middleware/HandleRunnerMiddlewareTest.php
  test/Unit/Runner/Promise/MultiPromiseTest.php
Labels: enhancement

#847 Fix phpunit concurrency issue
  appveyor.yml
  test/Unit/Runner/Promise/MultiPromiseTest.php
Labels: enhancement

#848 Upgrade paratest
  composer.json
Labels: enhancement

#850 Fix git hooks error if the path contains whitespace
  resources/hooks/local/commit-msg
  resources/hooks/local/pre-commit
Labels: bug
