Repository phpro/grumphp, pull requests merged in 2021-01, with the labels that each got.

#861 Fix --quiet bug during git stash pop
  src/Event/Subscriber/StashUnstagedChangesSubscriber.php
Labels: bug

#862 Only stop on failure for blocking failure results
  src/Runner/Middleware/HandleRunnerMiddleware.php
  test/Unit/Runner/Middleware/HandleRunnerMiddlewareTest.php
Labels: bug

#863 Pass $_ENV variables to amp/parallel callback
  doc/parameters.md
  src/Runner/TaskHandler/Middleware/ParallelProcessingMiddleware.php
Labels: bug

#868 Added jonmldr/grumphp-doctrine-task to extensions.md
  doc/extensions.md
Labels: Documentation

#872 Fix psalm errors
  src/Configuration/Compiler/TaskCompilerPass.php
  src/Configuration/Compiler/TestSuiteCompilerPass.php
Labels: enhancement

#842 Check config before skipping
  src/Task/PhpStan.php
  test/Unit/Task/PhpStanTest.php
Labels: enhancement

#867 Test should not fail because it didn't match everything in the whitelist
  doc/tasks/git_branch_name.md
  src/Task/Git/BranchName.php
  test/Unit/Task/Git/BranchNameTest.php
Labels: enhancement
