Repository phpro/grumphp, pull requests merged in 2022-11, with the labels that each got.

#1053 Support PHP 82 - Drop PHP 74
  .github/workflows/depsreview.yaml
  .github/workflows/grumphp.yml
  appveyor.yml
  composer.json
  resources/config/util.yml
Labels: enhancement

#1054 Add Rector Task
  composer.json
  doc/tasks.md
  doc/tasks/rector.md
  resources/config/tasks.yml
  src/Task/Rector.php
  test/Unit/Task/RectorTest.php
Labels: new feature

#1057 [Docs] Fix invalid Rector install command
  doc/tasks/rector.md
Labels: Documentation
