Repository phpro/grumphp, pull requests merged in 2022-02, with the labels that each got.

#981 Lock parallel functions
  composer.json
Labels: bug

#976 Lighter twigcs on precommit
  doc/tasks/twigcs.md
  src/Task/TwigCs.php
  test/Unit/Task/TwigCsTest.php
Labels: enhancement

#980 Change deptrac arguments according v0.19
  doc/tasks/deptrac.md
  src/Task/Deptrac.php
  test/Unit/Task/DeptracTest.php
Labels: enhancement

#986 Incorrect global install for eslint task
  doc/tasks/eslint.md
Labels: Documentation

#984 New `no-dev` option for local-php-security-checker
  doc/tasks/securitychecker/local.md
  src/Task/SecurityCheckerLocal.php
  test/Unit/Task/SecurityCheckerLocalTest.php
Labels: enhancement
